import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import { AppProviders } from "@/providers/app-providers";
import { TooltipProvider } from "@/components/ui/tooltip";
import "./globals.css";
import { getSession } from "@/lib/dal";
import { isDevAuthBypassEnabled } from "@/config/dev-auth-bypass";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { GlobalShellExclusions } from "@/components/global-shell-exclusions";
import SignoutButton from "./auth/_components/SignoutButton";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const currentUser = await getSession();
  const IsDevShowSignOutButton = false; // Set to true to show sign-out button in dev when bypass is enabled

  return (
    <html lang="en" className={inter.variable}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <div vaul-drawer-wrapper="" className="min-h-screen flex flex-col">
          <GlobalShellExclusions>
            <Header />
          </GlobalShellExclusions>
          <AppProviders>
            <TooltipProvider>
              {isDevAuthBypassEnabled ? (
                <div className="w-full bg-amber-200 px-4 py-2 text-center text-xs font-semibold tracking-wide text-amber-950">
                  DEV_AUTH_BYPASS is ON: authentication and route protection are
                  bypassed.
                </div>
              ) : null}
              <main className="flex-1 flex flex-col">{children}</main>
            </TooltipProvider>
          </AppProviders>
          <GlobalShellExclusions>
            <Footer />
          </GlobalShellExclusions>
        </div>
      </body>
    </html>
  );
}
